// Automatically generated by tomatebase-cli

import { TomateMappable, IpcCall } from "../../src";
import Boat, { BoatData } from "./boat";

export default class ShadowBoat implements TomateMappable {
  ipcCall: IpcCall;
  id: string;
  data: BoatData;
  static className = 'ThisIsABoat';
  constructor(
    ipcCall: IpcCall,
    data: BoatData | { data: BoatData; id: string }
  ) {
    this.ipcCall = ipcCall;

    if ('id' in data) {
      this.id = data.id;
      this.data = data.data;
      return;
    }

    this.data = data;
    this.id = 'temp-should-be-replaced-by-map';
  }
  doubleSpeed() {
    return this.data.speed * 2;
  }

  foo(_bar: string) {
    return this.ipcCall('db-function', 'foo', arguments);
  }

  toJSON() {
    return { data: { data: this.data, id: this.id }, class: Boat.className };
  }
}
